#!/usr/bin/env bash
# scripts/build_anykernel3.sh <variant-suffix>
# Produces out/<KERNEL_NAME>-<CODENAME>-<variant>-<date>.zip
set -euo pipefail

SUFFIX="${1:?usage: build_anykernel3.sh <variant-suffix>}"
: "${GITHUB_WORKSPACE:?}"
: "${KERNEL_NAME:?}"
: "${CODENAME:?}"
: "${ANYKERNEL_REPO:?}"
: "${ANYKERNEL_BRANCH:?}"

AK_DIR="$GITHUB_WORKSPACE/AnyKernel3"
rm -rf "$AK_DIR"
git clone --depth=1 -b "$ANYKERNEL_BRANCH" "$ANYKERNEL_REPO" "$AK_DIR"

# Strip the template's sample configs — we write our own below.
rm -f "$AK_DIR"/anykernel.sh.orig

cat > "$AK_DIR/anykernel.sh" <<EOF
# AnyKernel3 config — generated by scripts/build_anykernel3.sh
properties() { '
kernel.string=${KERNEL_NAME} for ${CODENAME}
do.devicecheck=1
do.modules=0
do.systemless=1
do.cleanup=1
do.cleanuponabort=0
device.name1=${CODENAME}
supported.versions=
supported.patchlevels=
'; }

block=/dev/block/bootdevice/by-name/boot;
is_slot_device=1;
ramdisk_compression=auto;

. tools/ak3-core.sh

dump_boot
write_boot
EOF

mkdir -p "$AK_DIR"
cp "$GITHUB_WORKSPACE"/out/Image "$AK_DIR/" 2>/dev/null || true
cp "$GITHUB_WORKSPACE"/out/*.dtb "$AK_DIR/" 2>/dev/null || true
find "$GITHUB_WORKSPACE/out" -iname '*dtbo*.img' -exec cp {} "$AK_DIR/dtbo.img" \; 2>/dev/null || true

DATE_TAG="$(date +%Y%m%d-%H%M)"
ZIP_NAME="${KERNEL_NAME}-${CODENAME}-${SUFFIX}-${DATE_TAG}.zip"

( cd "$AK_DIR" && zip -r9 -q "$GITHUB_WORKSPACE/$ZIP_NAME" . -x '.git/*' )

echo "path=$GITHUB_WORKSPACE/$ZIP_NAME" >> "$GITHUB_OUTPUT"
echo "name=$ZIP_NAME" >> "$GITHUB_OUTPUT"
echo "Packaged: $ZIP_NAME"
