#!/usr/bin/env bash
# scripts/build_anykernel3.sh <variant-suffix>
# Produces out/<KERNEL_NAME>-<CODENAME>-<variant>-<date>.zip
#
# anykernel.sh values below (block=boot, is_slot_device=auto,
# ramdisk_compression=auto, patch_vbmeta_flag=auto) match a proven
# working reference build for this same device — these are the AK3
# *symbolic* settings, which let ak3-core.sh auto-resolve the actual
# partition path (bootdevice/by-name, mapper, platform/*/by-name, ...)
# and A/B slot at flash time, instead of a single hardcoded path that
# only matches one specific partition layout/recovery combination.
set -euo pipefail

SUFFIX="${1:?usage: build_anykernel3.sh <variant-suffix>}"
: "${GITHUB_WORKSPACE:?}"
: "${KERNEL_NAME:?}"
: "${CODENAME:?}"
: "${ANYKERNEL_REPO:?}"
: "${ANYKERNEL_BRANCH:?}"
CODENAME_ALT="${CODENAME_ALT:-}"

AK_DIR="$GITHUB_WORKSPACE/AnyKernel3"
rm -rf "$AK_DIR"
git clone --depth=1 -b "$ANYKERNEL_BRANCH" "$ANYKERNEL_REPO" "$AK_DIR"

# Strip the template's sample configs — we write our own below.
rm -f "$AK_DIR"/anykernel.sh.orig

DEVICE_NAMES="device.name1=${CODENAME}"
[ -n "$CODENAME_ALT" ] && DEVICE_NAMES="${DEVICE_NAMES}
device.name2=${CODENAME_ALT}"

cat > "$AK_DIR/anykernel.sh" <<EOF
# AnyKernel3 config — generated by scripts/build_anykernel3.sh
properties() { '
kernel.string=${KERNEL_NAME} for ${CODENAME}
do.devicecheck=1
do.modules=0
do.systemless=1
do.cleanup=1
do.cleanuponabort=0
${DEVICE_NAMES}
supported.versions=
supported.patchlevels=
'; }

boot_attributes() {
  set_perm_recursive 0 0 755 644 \$RAMDISK/*;
  set_perm_recursive 0 0 750 750 \$RAMDISK/init* \$RAMDISK/sbin;
}

block=boot;
is_slot_device=auto;
no_block_display=1;
ramdisk_compression=auto;
patch_vbmeta_flag=auto;

. tools/ak3-core.sh

split_boot;
flash_boot;
flash_dtbo;
EOF

mkdir -p "$AK_DIR"
cp "$GITHUB_WORKSPACE"/out/Image "$AK_DIR/" 2>/dev/null || true
cp "$GITHUB_WORKSPACE"/out/*.dtb "$AK_DIR/" 2>/dev/null || true
find "$GITHUB_WORKSPACE/out" -iname '*dtbo*.img' -exec cp {} "$AK_DIR/dtbo.img" \; 2>/dev/null || true

DATE_TAG="$(date +%Y%m%d-%H%M)"
ZIP_NAME="${KERNEL_NAME}-${CODENAME}-${SUFFIX}-${DATE_TAG}.zip"

( cd "$AK_DIR" && zip -r9 -q "$GITHUB_WORKSPACE/$ZIP_NAME" . -x '.git/*' )

echo "path=$GITHUB_WORKSPACE/$ZIP_NAME" >> "$GITHUB_OUTPUT"
echo "name=$ZIP_NAME" >> "$GITHUB_OUTPUT"
echo "Packaged: $ZIP_NAME"
